version: '3'
services:
  user-app:
    restart: on-failure
    build: ./social-network-user
    deploy:
      replicas: 2
    networks:
      - socialnetwork
    volumes:
      - ./social-network-user/:/usr/src/app
    depends_on:
      - user-mongo

  user-nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./social-network-user/nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - socialnetwork  
    depends_on:
      - user-app

  user-mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27018"
    networks:
      - socialnetwork
    volumes:
      - ./social-network-user/mongo/data/db:/data/db

  post-app:
    restart: on-failure
    build: ./social-network-post
    deploy:
      replicas: 2
    networks:
      - socialnetwork
    volumes:
      - ./social-network-post/:/usr/src/app
    depends_on:
      - post-mongo

  post-nginx: 
    image: nginx:latest
    container_name: post-nginx
    volumes:
      - ./social-network-post/nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    networks:
      - socialnetwork  
    depends_on:
      - post-app

  post-mongo:
    container_name: post-mongo
    image: mongo
    ports:
      - "27021:27021"
    networks:
      - socialnetwork
    volumes:
      - ./social-network-post/mongo/data/db:/data/db
  
  like-app:
    restart: on-failure
    build: ./social-network-like
    deploy:
      replicas: 2
    networks:
      - socialnetwork
    volumes:
      - ./social-network-like/:/usr/src/app
    depends_on:
      - like-mongo

  like-nginx: 
    image: nginx:latest
    container_name: nginx-like
    volumes:
      - ./social-network-like/nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8083:80
    networks:
      - socialnetwork  
    depends_on:
      - like-app

  like-mongo:
    container_name: like-mongo
    image: mongo
    ports:
      - "27020:27020"
    networks:
      - socialnetwork
    volumes:
      - ./social-network-like/mongo/data/db:/data/db

  gateway-app:
    restart: on-failure
    build: ./social-network-gateway
    deploy:
      replicas: 2
    networks:
      - socialnetwork
    volumes:
      - ./social-network-gateway/:/usr/src/app

  gateway-nginx: 
    image: nginx:latest
    container_name: gateway-nginx
    volumes:
      - ./social-network-gateway/nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:80
    networks:
      - socialnetwork  
    depends_on:
      - gateway-app

  comment-app:
    restart: on-failure
    build: ./social-network-comment
    deploy:
      replicas: 2
    networks:
      - socialnetwork
    volumes:
      - ./social-network-comment/:/usr/src/app
    depends_on:
      - comment-mongo

  comment-nginx: 
    image: nginx:latest
    container_name: comment-nginx
    volumes:
      - ./social-network-comment/nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082:80
    networks:
      - socialnetwork  
    depends_on:
      - comment-app

  comment-mongo:
    container_name: comment-mongo
    image: mongo
    ports:
      - "27019:27019"
    networks:
      - socialnetwork
    volumes:
      - ./social-network-comment/mongo/data/db:/data/db
  
networks:
  socialnetwork:
    driver: bridge